default:
  max_age_seconds_open: 900
  max_age_seconds_closed: 86400
manual:
  max_age_seconds: 604800
markets:
  CN:
    max_age_seconds_open: 900
    max_age_seconds_closed: 86400
  HK:
    max_age_seconds_open: 900
    max_age_seconds_closed: 86400
  US:
    max_age_seconds_open: 900
    max_age_seconds_closed: 86400
  FX:
    max_age_seconds_open: 1800
    max_age_seconds_closed: 86400
